name: MultiHome
version: 0.3
main: net.madmanmarkau.MultiHome.MultiHome
author: MadManMarkAu
description: >
             Multiple home locations.
commands:
  multihome_home:
    description: Takes you back to your home location.
    aliases: home
    usage: /<command> [location_name]
  multihome_sethome:
    description: Sets your home location.
    aliases: sethome
    usage: /<command> [location_name]
